version: "3.6"
services:

    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        ports:
            - "1883:1883"
        volumes:
            - ./conf/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
        networks:
            - mqtt

    mqttx-web:
        image: emqx/mqttx-web
        container_name: mqttx-web
        ports:
            - "80:80"
        depends_on:
            - mosquitto
        networks:
            - mqtt

    ### DATABASE
    influxdb:
        image: influxdb:2
        container_name: influxdb
        ports:
            - "8083:8083"
            - "8086:8086"
            - "8090:8090"
        depends_on:
            - mosquitto
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: admin
            DOCKER_INFLUXDB_INIT_PASSWORD: Admin.123
            DOCKER_INFLUXDB_INIT_ORG: somorrostro
            DOCKER_INFLUXDB_INIT_BUCKET: pruebas-MIR-mqtt
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: -Kn9BQmY6lgwBTKpt1QZgbAOa4p8YrQ3YVGoKdH9G-U3g6Z5w97bJjVknHoZmTkqgN3uX428s1_x2MKYpU260g==
        networks:
            - db
        volumes:
            - ./data/influxdb/:/var/lib/influxdb

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        environment:
            # configuration in /telegraf/telegraf.conf
            influxdb_token: -Kn9BQmY6lgwBTKpt1QZgbAOa4p8YrQ3YVGoKdH9G-U3g6Z5w97bJjVknHoZmTkqgN3uX428s1_x2MKYpU260g==
        depends_on:
            - influxdb
            - mosquitto
        restart: unless-stopped
        networks:
            - mqtt
            - db
        volumes:
            - ./conf/telegraf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

    grafana:
        image: grafana/grafana
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_USERNAME=admin
            - GF_SECURITY_ADMIN_PASSWORD=1234
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/data:/var/lib/grafana
            - ./conf/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
        networks:
            - grafana
            - db
            - line
        depends_on:
            - telegraf
    # temperature-producer:
    #     build:
    #       context: ./DataSender
    #       dockerfile: dockerfile
    #     container_name: temperature-producer
    #     depends_on:
    #       - kafka1
    #     networks:
    #       - kafka

    ### NETWORKS
networks:
    mqtt:
        # connection to mqtt
        name: mqtt
        driver: bridge
    line:
        # connection to linesender
        name: line
        driver: bridge
    db:
        # connections to the database
        name: db
        driver: bridge
    grafana:
        name: grafana
        driver: bridge
